### ISSUE TITLE
First build

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/mist#1]
~~1. Remove DAO code~~
~~2. Fix Shifty~~
~~3. Fix rate conversion for balances~~
~~4. Inert Binaries~~
~~a.Windows~~
~~b.Darwin~~
~~c.Linux~~
5.Test
6.Build

**Comment by whatisgravity** [comment]
We may want to update the art, if anyone has time to contribute to the art upgrades please leave a comment. If you need assistance on finding the art that needs to be replaced just notify.

**Comment by realcodywburns** [comment]
I have some free time. I can start updating the art.

**Comment by whatisgravity** [comment]
Great, that would be really helpful. Just fork the existing project, make the changes and issue the pull request and I will merge it in.

**Comment by realcodywburns** [comment]
I have changed the icons and logos i could find. I issued them as a commit before i saw you message. all future ones will be on my fork.

**Comment by splix** [comment]
rel to rate conversion - https://min-api.cryptocompare.com/data/price?fsym=ETC&tsyms=BTC,USD,EUR

**Comment by whatisgravity** [comment]
@realcodywburns Thanks, I will make sure to check your forks before building. Thanks for dealing with the images, it is really appreciated.

@splix if you have time can you make the change for that and issue a pull request, if you dont have time I will make the change. I did a quick search over the code and did not find that, just found it in an old issue and commit which does not match the current file structure.

---

Since the build instructions don't include Linux I will need to add those, its fairly simple but it still should be included. Something feels wrong to me about building open source p2p financial software on OSX. I'm taking notes so I can alter the README to include the linux build instructions.

I'm pretty surprised to find out that the Mist developers have been collecting referral revenue from the shifty API, I don't think that was ever told to the community. I created an issue regarding this, for now I just made an API key so we can move forward. I will hand over whatever revenue is made but we need a better long term solution that provides transparent accounting of revenue generated.

Also recently just found that they were adding a contract deployed to the network, Ethereum Foundation developers need to fix this problem at a different level of the stack. I understand it as a stop gap solution but it is still a poor engineering choice, I'm generally against hacky/hamfisted solutions like this, but we can decide together if we want to adopt this for the next version or not.

---

I committed 99% of the remaining updates needed for the first builds.

The major remaining tasks involve building i386 binaries and publishing them and altering the gulp file.

**Comment by splix** [comment]
Sure, I'll try to fix rate conversion

**Comment by whatisgravity** [comment]
I managed to get the conversion rate tackled, and the binaries are now updated and switched to bz2 to require us to make as few changes as possible. The build should be ready soon.

**Comment by whatisgravity** [comment]
Should we change? https://github.com/ethereumproject/mist/blob/develop/interface/public/images/bg-metropolis.jpg

It does not currently match the new logo, it would be better in my opinion if the background matched the color scheme of the logo or was complementary to it.

**Comment by realcodywburns** [comment]
I had considered finding a similar building photographed at night to replace the BG image. As far as I know there is no reason for the buildings other than a visual indication of the contenuaton of moving from frontier to homestead to metropolis. As the events surrounding the transition to classic are technically the same as a version change; the background should be changed. Something that says 'classic' but does not really distract....

**Comment by whatisgravity** [comment]
Yeah, that is why I wasn't entirely sure, knowing it is an indicator of which rule set is currently active. It looks off but there are other considerations.

**Comment by realcodywburns** [comment]
Ethereum<sup>classic</sup> - the blind justice edition http://www.lawtechnologytoday.org/wp-content/uploads/2014/04/lady-justice.jpg

**Comment by whatisgravity** [comment]
I'm comfortable with the symbolism, my concern relates more to the design aspects of it not having a consistent color scheme though. It may be best to see if we can find the designer of the original artwork to extend it to cover that specific background asset.

**Comment by realcodywburns** [comment]
Which graphic is it pulling in for the splash screen?

edit found it. It looks like the logo for that is the icon2x. But for consistency I will redo the rest in a fork and see how it looks with out the black circle.

**Comment by whatisgravity** [comment]
It is this one: https://github.com/ethereumproject/mist/blob/develop/interface/public/images/bg-homestead.jpg

I was incorrect before.

**Comment by whatisgravity** [comment]
I need to either publish the meteor packages or preferably just call them locally or from the github repository. This will resolve the currency conversion. I believe that is the last issue aside from the OSX API key, which may need to be put off until next release.

**Comment by whatisgravity** [comment]
Testing the first build now, I found one issue but overall seems to be doing well.

**Comment by whatisgravity** [comment]
Currently, I'm considering releasing two versions, a version with some security enhancements and a version with all the convenience features enabled by default.

**Comment by realcodywburns** [comment]
Did you ever fix the shifty api issue?

**Comment by whatisgravity** [comment]
In the sense that I have it working, yes. However it introduces security issues for that feature to be enabled. Now that I have had more time to review the code, I believe an alternative GUI client with a focus on security is even more important. 

The larger remaining issue is the OSX API key needed to sign applications so they are not considered third party.

**Comment by whatisgravity** [comment]
Migrated the packages inside of the repo as submodules rather than using atmosphere. I think this makes development easier but it appears there is an issue, I'll fix it next time I'm free and generate builds for the first release.
