### ISSUE TITLE
win64 build

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/mist#10]
#### System information

```
Version: `0.8.1`
OS & Version: windows 64
Node type: `eth/getc(default)`
```

-the sig file wont verify
![image](https://cloud.githubusercontent.com/assets/13103499/17393844/c438f526-59eb-11e6-9236-1a185d581b68.png)
- Windows 10 also makes you side load the program on the first run because it is from an untrusted source.
- rhe win 64 build defaults to geth on the first run. The node folder only has eth. Renaming eth to gth "fixed" the problem and the program loaded and synced to the classic chain.

**Comment by whatisgravity** [comment]
Thanks for reporting this, the gulp build script is  in need a lot of maintenance, I will make the changes for this to build. 

I'm not very familiar with modern windows development, do I need need a key like with OSX. Or is this Kleopatra saying there is an error with the signature I provided?

**Comment by realcodywburns** [comment]
Im not sure, I usually pacman -S to install what i need ha ha. I have a few images and computers with just about the entire gambit for testing purposes. Windows has moved to a "certified developer program" like Mac from what I can tell, where only 'authorized' programmers can make install files. 
I am 90% sure it was the kleoptras fault it didnt recognize the sig. I was abe to verify it on my system.

**Comment by whatisgravity** [comment]
In between my other tasks I have been setting up some windows VMs to get a better idea of how to fix this issue.

**Comment by whatisgravity** [comment]
It should be working now, I tested both 32 and 64 bit builds. Closing this ticket, if you do have issues with this build reopen this ticket.
