### ISSUE TITLE
Linux Build: Invalid Version: 5cbe0c0

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/mist#12]
Need to investigate the update system check (semver.js)

**Comment by elaineo** [comment]
I don't see this issue. Does it still exist?

**Comment by whatisgravity** [comment]
I will check, but this occurred because Mist has an callback to an EF operated service to check the version so it will need to be fixed eventually. I will look for it and edit this reply to include the line number. 

geth uses a smart contract as a version oracle, it may be similar.

**Comment by mikeyb** [comment]
Please re-open with where you are stuck if this is still issue
