### ISSUE TITLE
Shifty API Key

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/mist#2]
For now I created a shifty API key, I'm uncomfortable collecting revenue by this existing in the client. I feel it was a bad idea for it to ever be in the client, it seems a bit underhanded since I don't think most users know the owner of the API key is collecting referral fees. I would like to see this feature removed or alternatively we need a transparent way to both collect and allocate revenue generated.

**Comment by yolandaruiz** [comment]
I agree that it feels inadequate.

**Comment by realcodywburns** [comment]
Heres a news story on the latest mist: Mist Developers Deliberately Use ShapeShift Affiliate Link For ETC Transactions

http://themerkle.com/mist-developers-deliberately-use-shapeshift-affiliate-link-for-etc-transactions/

**Comment by whatisgravity** [comment]
I decided to have two versions of Mist a essentially downstream clone and a security enhanced version. Eventually we should add more conversion options so we are not favoring any one conversion service. 

Proposals or changes to the plan can reopen this topic.
