### ISSUE TITLE
no linux build and no mist (yes, mist, MIST!!!) build

### ISSUE THREAD

**Issue by safinaskar** [ethereumproject/mist#33]
First, you don't provide recent linux build. You provide for linux 0.8.1 only. But it is sitting on wrong chain.
Second, you don't provide mist build. You provide ethereum wallet only. But mist and ethereum wallet are different things. Mist is dapp browser. And ethereum wallet doesn't contain dapp browser

**Comment by colibry545** [comment]
Most of our community members have Windows or Mac OS, so we only were able to make builds on these operation systems. Ethereum Classic is a Community-driven development project and if you would like to have Linux build you could help our community to make it. We would appreciate that. 

issue #35

**Comment by safinaskar** [comment]
At least write instructions for Linux users at release page. Say some quick-and-dirty way for them, for example: "Download Ethereum Classic Wallet 0.8.1 and replace geth binary with recent classic geth" (this works for me).

Also, please, provide mist builds (not ethereum wallet). At least for Windows and macOS (yeah, now we should call this OS so).
