### ISSUE TITLE
Mist browser hangs on startup ""Client binaries resolved. Checking network..."

### ISSUE THREAD

**Issue by fomosapiens** [ethereumproject/mist#40]
Update:

i was able to start successfully after downloading the geth manually and replacing it in "unpacked" folder. However keeping the issue open unless you think its resolved. 
Not sure what's happening but geth.exe was 0 bytes when i tried to run in a newly installed computer. i think you guys need to add more validation steps to make sure geth.exe is verified or something..

when i start the "Ethereum Classic Wallet.exe" it just hangs on "Client binaries resolved. Checking network..." startup screen. node.log is not being updated.

http://imgur.com/a/SxJue

also after i renamed entire Ethereum Classic folder under Appdata and rerun, the new error message says "Error running downloaded binary" Checking network...

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/getc(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereumproject/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log`
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by splix** [comment]
From twitter:
> Igor, i found the root cause to be geth.exe, i think classic client is not detecting OS correctly and downloads wrong version
> what i did was i downloaded manually from the json file and replaced it in "unpacked" directory. the client started successfully.
> and when i renamed my old classic folder in appdata the client complained "Error running downloaded binary" Checking network...
> so when i went to unpacked for some reason geth.exe was 0 bytes.. so not sure what happened. may be you may need to add validation

**Comment by splix** [comment]
It seem to be same issue as Snaproll had. Archive file got corrupted during transfer, or save, so unzip can't process it correctly and produces 0-size `geth.exe`

We need to figure out why it happens on window, @realcodywburns can you make some tests?

And to fix the issue we need to retry download when Mist cannot run executable

**Comment by manotroll** [comment]
I1224 14:28:43.120143 cmd/utils/flags.go:669] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I1224 14:28:43.168163 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\minerador\AppData\Roaming\Ethereum\chaindata
I1224 14:28:43.771181 ethdb/database.go:169] closed db:C:\Users\minerador\AppData\Roaming\Ethereum\chaindata
I1224 14:28:43.778178 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\minerador\AppData\Roaming\Ethereum\chaindata
I1224 14:28:44.123203 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\minerador\AppData\Roaming\Ethereum\dapp
I1224 14:28:44.138203 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I1224 14:28:44.140204 eth/backend.go:201] Blockchain DB Version: 3
I1224 14:28:44.149204 core/blockchain.go:206] Last header: #2872052 [d45c637f…] TD=46999092142825749190
I1224 14:28:44.150204 core/blockchain.go:207] Last block: #2870907 [8d1c120c…] TD=46986391602116629052
I1224 14:28:44.150204 core/blockchain.go:208] Fast block: #2870979 [50a7683c…] TD=46987201305137073890
I1224 14:28:44.154205 eth/handler.go:112] blockchain not empty, fast sync disabled
I1224 14:28:44.165205 p2p/server.go:313] Starting Server
I1224 14:28:45.295270 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv2-IP1
I1224 14:28:45.304273 p2p/discover/udp.go:217] Listening, enode://5f09903718b63d67a8ca072e1b71192a31dc7b03b67890fdb38f8ab802d19fa5ffc35b50a688b7a4464777899182d0e33b809cb8c68efb9f7f4bcd938b31082b@186.193.247.99:30303
I1224 14:28:45.319269 p2p/server.go:556] Listening on [::]:30303
I1224 14:28:45.336273 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I1224 14:28:45.556286 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv2-IP1
I1224 14:28:55.329855 eth/downloader/downloader.go:320] Block synchronisation started
E1224 14:31:40.025749 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:31:40.025749 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:36:29.038639 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:36:29.038639 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:36:55.770202 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:36:55.770202 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:37:11.536124 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:37:11.536124 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:37:20.766663 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:37:20.766663 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:37:49.010313 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:37:49.010313 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:38:17.762995 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:38:17.767997 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:38:24.572393 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:38:24.572393 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:39:09.157998 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:39:09.157998 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:39:40.533833 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:39:40.533833 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:39:52.579537 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:39:52.581538 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:40:41.034369 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:40:41.035371 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:42:15.502890 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:42:15.507893 core/blockchain.go:1128]     gas used error (151880 / 146330)
I1224 14:44:57.213366 eth/downloader/downloader.go:1195] Peer 41117aaab3879086 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 8.243987567s]: potential rewrite attack: #2780907 [00000000…] <= #2780907 limit
E1224 14:45:04.046761 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:45:04.048764 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:46:41.649465 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:46:41.649465 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:46:59.656520 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:46:59.656520 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:49:03.699768 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:49:03.699768 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:50:10.571677 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:50:10.571677 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:51:18.406966 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:51:18.406966 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:53:18.999485 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:53:18.999485 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:55:46.994690 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:55:46.994690 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:56:53.613971 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:56:53.613971 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 14:59:25.554911 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 14:59:25.554911 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:01:52.396145 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:01:52.396145 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:03:10.129685 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:03:10.135688 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:07:35.648391 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:07:35.648391 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:08:19.605958 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:08:19.605958 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:09:49.407455 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:09:49.407455 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:09:59.710058 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:09:59.710058 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:10:19.779233 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:10:19.779233 core/blockchain.go:1128]     gas used error (151880 / 146330)
E1224 15:10:43.303606 core/blockchain.go:1127] Bad block #2870908 (0xb146c8a3742c3ea386f292724391e47b68648c2a903ae56c55fb4e546e21673a)
E1224 15:10:43.304609 core/blockchain.go:1128]     gas used error (151880 / 146330)

**Comment by khpool** [comment]
Friend
How to start it?  Thank you

**Comment by manotroll** [comment]
use jax

**Comment by fomosapiens** [comment]
@atiger7758 
download geth manually from here https://dl.bintray.com/ethereumproject/GoEthereumClassic/
don't forget to upload the binary to virustotal.com and verify its sha256 hash.
place it in C:\Users\YOURUSERID\AppData\Roaming\Ethereum Classic Wallet\binaries\Geth\unpacked
not sure about other platforms but you search in Linux with "find / -name geth"
