### ISSUE TITLE
stuck at 30804000

### ISSUE THREAD

**Issue by madtomic** [ethereumproject/mist#41]
Using Ethereum Classic Wallet 0.9.1 (Pre Release)

It seems to stuck at block 30804000

*This is to sync from scratch.

**Comment by madtomic** [comment]
Am also stuck with Ethereum Classic Mist Wallet - 0.8.1 (1.4.10 go-ethereum)

Can someone help?

**Comment by madtomic** [comment]
![image](https://cloud.githubusercontent.com/assets/6004542/22372850/098f6e32-e46d-11e6-88ca-8aa1ae3cb160.png)

Using the latest Ethereum Classic Geth 3.2.3

**Comment by mikeyb** [comment]
That is the latest block, you are not stuck.  You can view current block height at http://gastracker.io/
