### ISSUE TITLE
 How to run it LINUX 64bit

### ISSUE THREAD

**Issue by khpool** [ethereumproject/mist#42]
According to your instructions, but still can not start it
Can you tell me how to run ETC  谢谢
atiger7758@163.com

root@iZm5e2xixm1mn0xfljkpdsZ:~/Ethereum-Wallet-linux64-0-8-1# ls
AUTHORS		   libnode.so		   README.txt
content_shell.pak  LICENSE		   resources
Ethereum-Wallet    LICENSES.chromium.html  snapshot_blob.bin
icudtl.dat	   locales		   version
libffmpeg.so	   natives_blob.bin
root@iZm5e2xixm1mn0xfljkpdsZ:~/Ethereum-Wallet-linux64-0-8-1#

**Comment by mikeyb** [comment]
errors are helpful, or any type of information for that matter.  "can not start it" gives nothing to go on.

**Comment by khpool** [comment]
How to start it?
