### ISSUE TITLE
ETH and ETC wallets are same?

### ISSUE THREAD

**Issue by orkobar** [ethereumproject/mist#45]
I have an ETH mist wallet downloaded from here and today i purchased some ETC. Again i downloaded mist wallet, suprisingly they are close to each other.

When ı opened both of them at the same time, ı can see ETC account on ETH wallet, and see ETH account on ETC wallet.

Is it normal?

And what if i sent ETH on ETC account or reverse, accidentaly?

Regards

Orkun

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/getc(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereumproject/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log`
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by mikeyb** [comment]
You need to use a different datadir for each.

**Comment by orkobar** [comment]
Dear mikeyb

As you see i am not familiar to the system. Could you please define more specific. What is datadir? Am i need to do something different from default?

Both eth Wallet and etc wallet create a New account. I have some ethereum in eth wallet Sencronyzed.  Will it cause a problem if i sent etc to account Ethichr is created by etc wallet?

**Comment by orkobar** [comment]
Sorry ethichr is a wrong spell it must be "which"

**Comment by orkobar** [comment]
Hey Mikeyb

My eth wallet directory and etc wallet directory ( includes exe files ) are different but keystore in 
C:\Users\orkun\AppData\Roaming\Ethereum\keystore is same.

is it ok?

**Comment by ghost** [comment]
I too have this issue, however i also have the ETH Mist wallet installed.... do i need to uninstall that one and just have this mist wallet installed? Also what do you mean by a seperate Datadir?

**Comment by arvicco** [comment]
So far as I know Mist is not supported by ETC developers. Its replacement is soon-to-be-released Emerald Wallet: https://github.com/ethereumproject/emerald-wallet
