### ISSUE TITLE
Ethereum node connection error

### ISSUE THREAD

**Issue by Floreee** [ethereumproject/mist#47]
Hey there, 

I can't get my Ethereum Classic Wallet to connect. 
There is always the error like in the screenshot. 

![bildschirmfoto 2017-03-28 um 22 56 06](https://cloud.githubusercontent.com/assets/26751361/24427585/c20674a6-140b-11e7-9d2a-7e2180d1686d.png)
![bildschirmfoto 2017-03-28 um 23 02 34](https://cloud.githubusercontent.com/assets/26751361/24427586/c22a3788-140b-11e7-9837-bd43e4cda36c.png)

#### System information
``````
Version: `0.9.1`
OS & Version: osx
Node type: `eth/getc(default)`
``````

**Comment by Floreee** [comment]
No one? What's going on?

**Comment by splix** [comment]
It seems that your database is corrupted, I suggest to delete files under `%APPDATA%\Ethereum\{chaindata,blockchain}` and start again

**Comment by Floreee** [comment]
I did that several times.. but no change!

**Comment by splix** [comment]
I also noticed that you're using custom Geth build from sources. There're many things that can affect resulting binary. I suggest to try with official release of Classic Geth

**Comment by johnbailon** [comment]
Experienced same problem on Mac OS with [Ethereum Classic Wallet 0.9.1 (Pre Release)](https://github.com/ethereumproject/mist/releases/tag/v0.9.1pre). Used [Ethereum Classic Mist Wallet - 0.8.1 (1.4.10 go-ethereum)](https://github.com/ethereumproject/mist/releases/tag/5cbe0c0) instead.

**Comment by ghost** [comment]
still broken wont connect

**Comment by ghost** [comment]
yep same problem here, any solutions?

**Comment by PlantDr430** [comment]
I have the same problem. I have MIST V0.8.10 installed and the blockchain completely synced. I then re-named my %APPDATA%\Ethereum to Ethereum-ETH and installed Ethereum Classic Wallet 0.9.1 and ran Geth v1.6.5 to create a new %APPDATA%\Ethereum which I will use for ETC. I then tried to run Ethereum Classic Wallet 0.9.1 and I got the "Ethereum Node Connection Error"

**Comment by PlantDr430** [comment]
I even tried using a brand new computer. Downloaded Ethereum Classic Wallet 0.9.1 and tried to open it up, and I got the same "Ethereum Node Connection Error". Both attempts have been on Windows 10 64 bit.
