### ISSUE TITLE
github references

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/mist#5]
Internal references to "git://github.com/ethereum/mist' should be changed to point to "git://github.com/ethereumproject/mist" to ensure updates are received sans-fork.

**Comment by whatisgravity** [comment]
This is required for the build, it will be fixed in the process of creating the builds.

Thanks for fixing the README. Any other changes/improvements to the README are appreciated.

**Comment by whatisgravity** [comment]
Migrating README changes to https://github.com/ethereumproject/mist/issues/14
