### ISSUE TITLE
update TX etherscan.io URL

### ISSUE THREAD

**Issue by fomosapiens** [ethereumproject/mist#52]
Hi

TX ids are still going to outdated or unsupported etherescan.io explorer which says unable to locate transaction entry. Please refer to screenshots. i think that should open up to date explorers like gastracker.io.

<a href='https://postimg.org/image/l4yxudtyn/' target='_blank'><img src='https://s3.postimg.org/b7nx1bmcz/image.png' border='0' alt="1"/></a><br/><br/>
<a href='https://postimg.org/image/4363saf3j/' target='_blank'><img src='https://s3.postimg.org/l3p00ys4z/image.png' border='0' alt="2"/></a><br/><br/>
<a href='https://postimg.org/image/tbqxlyk1b/' target='_blank'><img src='https://s3.postimg.org/yaeg0hnub/Screenshot_7.png' border='0' alt="Screenshot_7"/></a><br/><br/>

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/getc(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereumproject/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log`
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by mikeyb** [comment]
Please re-open with where you are stuck if this is still issue
