### ISSUE TITLE
Can't Send ETC from Mist Wallet

### ISSUE THREAD

**Issue by smurphy165** [ethereumproject/mist#53]
Unable to send ETC from Mist Wallet v0.8.10 on Windows 64. Have not yet upgraded to Mist v0.9.0.

1 Bought Ether in Presale
2 Downloaded Mist Wallet
3 Successfully Transferred PreSale Ether into Mist Wallet | Verified X ETH in Main Account (Etherbase)
4 Added REPLAYSAFESPLIT to Mist Wallet
5 Added new account ETC DEPOSIT ACCOUNT to Mist Wallet
6 Added new account ETH DEPOSIT ACCOUNT to Mist Wallet
7 Deployed REPLAYSAFESPLIT on a small volume as follows:   
     -  Selected Split under Select Function
     -  Target Fork Address equals ETH DEPOSIT ACCOUNT
     -  Target No Fork Address equals ETC DEPOSIT ACCOUNT
     -  Selected EXECUTE, Transaction processed.
8 Using https://gastracker.io/ , verified:
     - ETH DEPOSIT ACCOUNT held Y ETH (hardfork balance)
     - Main Account (Etherbase) X-Y ETH (hardfork balance)  and  X ETC
     - ETC DEPOSIT ACCOUNT held zero ETC
9 Repeated Step 7 and 8 deploying REPLAYSAFESPLITV2,  Same result as in Step 8.
10 Deployed Send Function to Send ETH or ETC to Poloniex, Kraken, and Bitfinex Exchanges. Tried ShapeShift to convert to BTC. Verified successful transfers of ETH to two exchanges.   Unable to transfer ETC to any exchange (currently accepting ETC) or to ShapeShift. ETH is in the Send From Account to pay for gas.
11 Current Status:
     - Main Account (Etherbase)   X ETC and X-Y ETH
     - ETH DEPOSIT ACCOUNT   Y ETH
     - ETC DEPOSIT ACCOUNT   Zero ETC    
12 Goal is to transfer ETC to an exchange.

Thx in advance for assist.

**Comment by mikeyb** [comment]
Please re-open with where you are stuck if this is still issue
