### ISSUE TITLE
sent etc to eth wallet don't receive anything is there a way to recover this? I loose a lot of money I send so many erc token my ether metafox wallet I thought that etc would go in eth wallet

### ISSUE THREAD

**Issue by KingViet** [ethereumproject/mist#57]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/getc(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereumproject/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log`
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by mikeyb** [comment]
Whatever address you sent to, is the address that holds the tokens.  If you broadcasted on the ETH network, they are on the ETH network.  If you broadcasted on the ETC network, they are on the ETC network.

This is for issue tracking of bugs, not support for user errors
